version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "3000"
    # 필요하면 env
    env_file:
      - ./backend/.env
    # environment:
    #   - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "80:80"         # 로컬에서 http://localhost 로 접속
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
